### ISSUE TITLE
Rouge syntax highlighter

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-qsim-runner#11]
We need to implement and use a Rouge highlighter with QSIM. It could be based on NASM highlighter

**Comment by Charlyzzz** [comment]
This issue needs to be closed

**Comment by faloi** [comment]
> This issue needs to be closed

@Charlyzzz: if you consider this done, please close it.

**Comment by flbulgarelli** [comment]
Were we able to test in laboratory?

**Comment by Charlyzzz** [comment]
It works, but the github theme needs some tweaking (inside Rouge repo).

**Comment by Charlyzzz** [comment]
Bump @faloi @flbulgarelli

**Comment by faloi** [comment]
What do you mean by "some tweaking"? Can you provide a screenshot of the current state?

**Comment by flbulgarelli** [comment]
I have just one question: does QSim support hex literals? @Charlyzzz @faloi 


```asm
MOV R4, 0x5
ADD R3, R6
SUB R5, R2
JMP R5, R6
```

If it is NOT the case, I think we are done: https://github.com/mumuki/mumuki-laboratory/pull/766

**Comment by faloi** [comment]
Yep, it supports them, with that syntax.

**Comment by flbulgarelli** [comment]
Ok, so we have to add them to the lexer.

**Comment by Charlyzzz** [comment]
They are supported, but only in this format `0x****` and letters in uppercase. Would you like me to change it?

**Comment by flbulgarelli** [comment]
> They are supported, but only in this format 0x**** and letters in uppercase. Would you like me to change it?

Ok, so the problem is the number of digits, and that I tested this issue using a wrong example. So I think we can close it.
