### ISSUE TITLE
MUL hates R7

### ISSUE THREAD

**Issue by felipecalvo** [mumuki/mumuki-qsim-runner#25]
Can't really say if it hates it or not, but at the very least the MUL instruction does not seem to be working with register R7. That's kinda specific so I'm thinking there might be more cases I'm not finding.

```
MUL R2, 0x0002
```

is working, but 

```
MUL R7, 0x0002
```
is failing with the following message:

![image](https://user-images.githubusercontent.com/11304439/54150081-62426b00-4416-11e9-858e-5de2f3cb4d4d.png)

However, other instructions using register R7 do work, such as

```
ADD R7, 0x0002
SUB R7, 0x0002
DIV R7, 0x0002
MOV R7, 0x0002
```
On the other hand, `MUL R2, R7` works but `MUL R7, R2` doesn't.

Here's an exercise where you have to use both MUL and R7: https://mumuki.io/staging/exercises/7255-arquitectura-de-computadoras-registros-instrucciones-y-ensamblado-duplicar

**Comment by julian-berbel** [comment]
I modified the runqsim file to print the contents of qsim0 and qsim1 and then I sent a solution using R2 and then the same solution using R7.

The only difference in those files were the record number as expected, so as far as I can tell this seems to be a bug with the QSim.jar we're using. I don't think we can fix this ourselves.

**Comment by julian-berbel** [comment]
not really sure why, but this seems to be on purpose:
https://github.com/Orga-UNQ/qsim/blob/96fec88951be2f36c5880e2b4ec29a3502a44994/src/main/scala/ar/edu/unq/tpi/qsim/parser/Ensamblador.scala#L45-L57

**Comment by felipecalvo** [comment]
Seems like it's out of our reach so I'm closing this for~ever~ now.
